<a href="https://colab.research.google.com/github/MdAshekMahmud/Machine-Learning/blob/main/%5Cnotebooks%5CPandas_DataFrame_GFK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# [Creating a Pandas DataFrame](https://www.geeksforgeeks.org/pandas/creating-a-pandas-dataframe/)

A Pandas DataFrame is a data structure for storing and manipulating data in a table format (rows and columns), similar to Excel or SQL. It makes handling, filtering and analyzing large datasets easy. A DataFrame can be created using various data structures like lists, dictionaries, NumPy arrays etc.

In [ ]:
df = pd.DataFrame() # Empty DataFrame

## Creating DataFrame from list

* Each item in the list becomes a row.
* The DataFrame consists of a single unnamed column.

In [ ]:
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks']
df = pd.DataFrame(lst)
print(df)

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

## Creating DataFrame from dict of Numpy Array

We can create a Pandas DataFrame using a dictionary of NumPy arrays. Each key in the dictionary represents a column name and the corresponding NumPy array provides the values for that column.

In [ ]:
data = {
         'A': np.array([1, 4, 7]),
         'B': np.array([2, 5, 8]),
         'C': np.array([3, 6, 9])
}
df = pd.DataFrame(data)
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

## Creating a DataFrame from a List of Dictionaries

We can create a DataFrame using a list of dictionaries, where each dictionary represents a row. This is useful for handling structured data from APIs or JSON, and is commonly used in web scraping and API processing.

shift + alt + backspace

ctrl + shift + m

In [ ]:
data = [
    {'name': 'Mike', 'degree': 'MBA', 'score': 90},
    {'name': 'Dan', 'degree': 'BCA', 'score': 40},
    {'name': 'Emilia', 'degree': 'M.Tech', 'score': 80},
]
df = pd.DataFrame(data)
print(df)

     name  degree  score
0    Mike     MBA     90
1     Dan     BCA     40
2  Emilia  M.Tech     80

In [ ]:
import pandas as pd

data = {
    'name': ['Mike', 'Dan', 'Emillia'],
    'degree': ['MBA', 'BCA', 'M.Tech'],
    'score': [90, 40, 80]
}

df = pd.DataFrame(data)
print(df)

      name  degree  score
0     Mike     MBA     90
1      Dan     BCA     40
2  Emillia  M.Tech     80

# Pandas Dataframe Index

## Accessing and Modifying the Index

In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df.index)  # Accessing the index

RangeIndex(start=0, stop=5, step=1)

## Setting a Custom Index

In [ ]:
# Set 'Name' column as the index
df_with_index = df.set_index('Name')
print(df_with_index)

         Age  Gender  Salary
Name
John      25    Male   50000
Alice     30  Female   55000
Bob       22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000

## Resetting the Index

In [ ]:
# Reset the index back to the default integer index
df_reset = df.reset_index(drop=True)
df_reset

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

## Indexing with loc

<h3>The loc[] method in pandas allows to access rows and columns of a dataFrame using their labels, making it easy to retrieve specific data points.</h3>

In [ ]:
df_indexed = df.set_index('Name')
row = df_indexed.loc['Alice']
print(row)

Age           30
Gender    Female
Salary     55000
Name: Alice, dtype: object

In [ ]:
row = df.loc[1]
print(row)

Name       Alice
Age           30
Gender    Female
Salary     55000
Name: 1, dtype: object

In [ ]:
column = df.loc[:, 'Age']
column

0    25
1    30
2    22
3    35
4    28
Name: Age, dtype: int64

In [ ]:
df_indexed = df.set_index('Age')
df_indexed

        Name  Gender  Salary
Age
25      John    Male   50000
30     Alice  Female   55000
22       Bob    Male   40000
35       Eve  Female   70000
28   Charlie    Male   48000

## Pandas Access DataFrame

In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
# Display the entire DataFrame
print(df)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

## Accessing Columns From DataFrame

In [ ]:
# Access the 'Age' column
age_column = df['Age']
print(age_column)

0    25
1    30
2    22
3    35
4    28
Name: Age, dtype: int64

## Accessing Rows by Index

To access specific rows in a DataFrame, you can use iloc (for positional indexing) or loc (for label-based indexing). These methods allow you to retrieve rows based on their index positions or labels.

In [ ]:
# Access the row at index 1 (second row)
second_row = df.iloc[1]
print(second_row)

Name       Alice
Age           30
Gender    Female
Salary     55000
Name: 1, dtype: object

## Accessing Multiple Rows or Columns

You can access multiple rows or columns at once by passing a list of column names or index positions. This is useful when you need to select several columns or rows for further analysis.

In [ ]:
# Access the first three rows and the 'Name' and 'Age' columns
subset = df.loc[0:2, ['Name', 'Age']]
print(subset)

    Name  Age
0   John   25
1  Alice   30
2    Bob   22

## Accessing Rows Based on Conditions

In [ ]:
# Access rows where 'Age' is greater than 25
filtered_data = df[df['Age'] > 25]
print(filtered_data)

      Name  Age  Gender  Salary
1    Alice   30  Female   55000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

## Accessing Specific Cells with at and iat


If you need to access a specific cell, you can use the .at[] method for label-based indexing and the .iat[] method for integer position-based indexing. These are optimized for fast access to <b>single values</b>.

```
Pandas Dataframe.at[ ]
Syntax: Dataframe.at[position, label]
Parameters:
position: Position of element in column
label: Column name to be used
Return type: Single element at passed position
```

In [ ]:
# Access the 'Salary' of the row with label 2
salary_at_index_2 = df.at[2, 'Salary']
print(salary_at_index_2)

40000

```
Pandas Dataframe.iat[ ]
Syntax: Dataframe.iat[row, column]
Parameters:
position: Position of element in column
label: Position of element in row
Return type: Single element at passed position
```

In [ ]:
salary_at_index_2 = df.iat[2, 1]
print(salary_at_index_2)

22

# Indexing and Selecting Data with Pandas

## Indexing Data using the [] Operator

The [] operator is the basic and frequently used method for indexing in Pandas. It allows us to select columns and filter rows based on conditions. This method can be used to select individual columns or multiple columns.

### 1. Selecting a Single Column

To select a single column, we simply refer the column name inside square brackets.

In [ ]:
# Selecting a single column
data = pd.read_csv('/content/nba.csv', index_col='Name')

print("Dataset")
display(data.head(5))

first = data["Age"]
print("\nSingle Column selected from Dataset")
display(first.head(5))

Dataset

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

Single Column selected from Dataset

Name
Avery Bradley    25.0
Jae Crowder      25.0
John Holland     27.0
R.J. Hunter      22.0
Jonas Jerebko    29.0
Name: Age, dtype: float64

### 2. Selecting Multiple Columns

To select multiple columns, pass a list of column names inside the [] operator:

In [ ]:
first = data[["Age", "College", "Salary"]]
print("\nMultiple Columns selected from Dataset")
display(first.head(5))

Multiple Columns selected from Dataset

                Age            College     Salary
Name
Avery Bradley  25.0              Texas  7730337.0
Jae Crowder    25.0          Marquette  6796117.0
John Holland   27.0  Boston University        NaN
R.J. Hunter    22.0      Georgia State  1148640.0
Jonas Jerebko  29.0                NaN  5000000.0

## Indexing with .loc[ ]


The **.loc[]** function is used for label-based indexing. It allows us to access rows and columns by their labels. Unlike the indexing operator, it can select subsets of rows and columns simultaneously which offers flexibility in data retrieval.

### 1. Selecting a Single Row by Label

We can select a single row by its label:

In [ ]:
# Selecting a Single row by Label

row = data.loc["Avery Bradley"]
print(row)

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object

### 2. Selecting Multiple Rows by Label

To select multiple rows, pass a list of labels:

In [ ]:
rows = data.loc[["Avery Bradley", "R.J. Hunter"]]
print(rows)

                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0

                     College     Salary
Name
Avery Bradley          Texas  7730337.0
R.J. Hunter    Georgia State  1148640.0

### 3. Selecting Specific Rows and Columns

We can select specific rows and columns by providing lists of row labels and column names:

Dataframe.loc[["row1", "row2"], ["column1", "column2", "column3"]]

In [ ]:
selection = data.loc[["Avery Bradley", "R.J. Hunter"], ["Team", "Number", "Position"]]
print(selection)

                         Team  Number Position
Name
Avery Bradley  Boston Celtics     0.0       PG
R.J. Hunter    Boston Celtics    28.0       SG

### 4. Selecting All Rows and Specific Columns

We can select all rows and specific columns by using a colon [:] to indicate all rows followed by the list of column names:

Dataframe.loc[:, ["column1", "column2", "column3"]]

In [ ]:
all_rows_specific_columns = data.loc[:, ["Team", "Position", "Salary"]]
print(all_rows_specific_columns.head(5))

                         Team Position     Salary
Name
Avery Bradley  Boston Celtics       PG  7730337.0
Jae Crowder    Boston Celtics       SF  6796117.0
John Holland   Boston Celtics       SG        NaN
R.J. Hunter    Boston Celtics       SG  1148640.0
Jonas Jerebko  Boston Celtics       PF  5000000.0

### 5. Indexing with .iloc[ ]

The .iloc[] function is used for position-based indexing. It allows us to access rows and columns by their integer positions. It is similar to .loc[] but only accepts integer-based indices to specify rows and columns.

#### 1. Selecting a Single Row by Position
To select a single row using .iloc[] provide the integer position of the row:

In [ ]:
row = data.iloc[3]
print(row)

Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object

#### 2. Selecting Multiple Rows by Position</h2>

We can select multiple rows by passing a list of integer positions:

In [ ]:
rows = data.iloc[[3, 5, 7]]
print(rows)

                        Team  Number Position   Age Height  Weight  \
Name
R.J. Hunter   Boston Celtics    28.0       SG  22.0    6-5   185.0
Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0

                    College      Salary
Name
R.J. Hunter   Georgia State   1148640.0
Amir Johnson            NaN  12000000.0
Kelly Olynyk        Gonzaga   2165160.0

#### 3. Selecting Specific Rows and Columns by Position

We can select specific rows and columns by providing integer positions for both rows and columns:

In [ ]:
# data.iloc[[row], [column]]
selection = data.iloc[[3, 4], [1, 2]]
print(selection)

               Number Position
Name
R.J. Hunter      28.0       SG
Jonas Jerebko     8.0       PF

####4. Selecting All Rows and Specific Columns by Position

To select all rows and specific columns, use a colon [:] for all rows and a list of column positions:

In [ ]:
selection = data.iloc[:, [1, 2]]
print(selection)

               Number Position
Name
Avery Bradley     0.0       PG
Jae Crowder      99.0       SF
John Holland     30.0       SG
R.J. Hunter      28.0       SG
Jonas Jerebko     8.0       PF
...               ...      ...
Shelvin Mack      8.0       PG
Raul Neto        25.0       PG
Tibor Pleiss     21.0        C
Jeff Withey      24.0        C
NaN               NaN      NaN

[458 rows x 2 columns]

## 4. Other Useful Indexing Methods

Pandas also provides several other methods that we may find useful for indexing and manipulating DataFrames:

### 1. <b>.head()</b>: Returns the first n rows of a DataFrame

In [ ]:
print(data.head(2))

                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0

                 College     Salary
Name
Avery Bradley      Texas  7730337.0
Jae Crowder    Marquette  6796117.0

### 2. <b>.tail()</b>: Returns the last n rows of a DataFrame

In [ ]:
print(data.tail(2))

                  Team  Number Position   Age Height  Weight College    Salary
Name
Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas  947276.0
NaN                NaN     NaN      NaN   NaN    NaN     NaN     NaN       NaN

### 3. <b>.at()</b>: Access a single value for a row/column label pair

In [ ]:
vlaue = data.at["Avery Bradley", "Age"]
print(vlaue)

25.0

### 4. <b>.query():</b> Query the DataFrame using a boolean expression

In [ ]:
result = data.query("Age > 25 and College == 'Duke'")
print(result)

                                    Team  Number Position   Age Height  \
Name
Lance Thomas             New York Knicks    42.0       SF  28.0    6-8
Elton Brand           Philadelphia 76ers    42.0       PF  37.0    6-9
JJ Redick           Los Angeles Clippers     4.0       SG  31.0    6-4
Mike Dunleavy              Chicago Bulls    34.0       SG  35.0    6-9
Dahntay Jones        Cleveland Cavaliers    30.0       SG  35.0    6-6
Miles Plumlee            Milwaukee Bucks    18.0        C  27.0   6-11
Luol Deng                     Miami Heat     9.0       SF  31.0    6-9
Josh McRoberts                Miami Heat     4.0       PF  29.0   6-10
Kyle Singler       Oklahoma City Thunder     5.0       SF  28.0    6-8
Gerald Henderson  Portland Trail Blazers     9.0       SG  28.0    6-5
Mason Plumlee     Portland Trail Blazers    24.0        C  26.0   6-11

                  Weight College      Salary
Name
Lance Thomas       235.0    Duke   1636842.0
Elton Brand        254.0    Duke         NaN
JJ Redick          190.0    Duke   7085000.0
Mike Dunleavy      230.0    Duke   4500000.0
Dahntay Jones      225.0    Duke         NaN
Miles Plumlee      249.0    Duke   2109294.0
Luol Deng          220.0    Duke  10151612.0
Josh McRoberts     240.0    Duke   5543725.0
Kyle Singler       228.0    Duke   4500000.0
Gerald Henderson   215.0    Duke   6000000.0
Mason Plumlee      235.0    Duke   1415520.0

## Pandas dataframe.get()

In [ ]:
df = pd.read_csv("/content/nba.csv")
df.get("Salary")
df.get(["Salary", "Team", "Name"])

        Salary            Team           Name
0    7730337.0  Boston Celtics  Avery Bradley
1    6796117.0  Boston Celtics    Jae Crowder
2          NaN  Boston Celtics   John Holland
3    1148640.0  Boston Celtics    R.J. Hunter
4    5000000.0  Boston Celtics  Jonas Jerebko
..         ...             ...            ...
453  2433333.0       Utah Jazz   Shelvin Mack
454   900000.0       Utah Jazz      Raul Neto
455  2900000.0       Utah Jazz   Tibor Pleiss
456   947276.0       Utah Jazz    Jeff Withey
457        NaN             NaN            NaN

[458 rows x 3 columns]

## Python | Pandas DataFrame.isin()

**isin() Function in Pandas Examples**

The DataFrame.isin() method in Pandas is a powerful tool for filtering and selecting data within a DataFrame based on specified conditions. It allows you to create boolean masks to identify rows where the values in one or more columns match certain criteria. Let's delve into the details of the isin() method

* Single Parameter Filtering
* Multiple Parameter Filtering


**Single Parameter filtering Using Pandas DataFrame.isin()**


In the following example, Rows are checked and a boolean series is returned which is True wherever Gender="Male". Then the series is passed to the data frame to see new filtered data frame.

In [ ]:
# making data frame from csv file
data = pd.read_csv("/content/employees.csv")

# creating a bool series from isin()
new = data["Gender"].isin(["Male"])

# displaying data with gender = male only
filtered_data = data[new]
print(filtered_data.head())

  First Name Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas   Male   8/6/1993        12:42 PM   97308    6.945
1     Thomas   Male  3/31/1996         6:53 AM   61933    4.170
3      Jerry   Male   3/4/2005         1:00 PM  138705    9.340
4      Larry   Male  1/24/1998         4:47 PM  101004    1.389
5     Dennis   Male  4/18/1987         1:35 AM  115163   10.125

  Senior Management             Team
0              True        Marketing
1              True              NaN
3              True          Finance
4              True  Client Services
5             False            Legal

**Multiple parameter Filtering Using Pandas DataFrame.isin()**

In [ ]:
# creating filters of bool series from isin()

filter1 = data["Gender"].isin(["Female"])
filter2 = data["Team"].isin(["Engineering", "Distribution", "Finance"])

filtered_data = data[filter1 & filter2]

print(filtered_data.head())

   First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
2       Maria  Female   4/23/1993        11:17 AM  130590   11.858
7         NaN  Female   7/20/2015        10:43 AM   45906   11.598
8      Angela  Female  11/22/2005         6:29 AM   95570   18.523
14   Kimberly  Female   1/14/1999         7:13 AM   41426   14.543
30  Christina  Female    8/6/2002         1:19 PM  118780    9.096

   Senior Management         Team
2              False      Finance
7                NaN      Finance
8               True  Engineering
14              True      Finance
30              True  Engineering

# [Slicing Pandas Dataframe](https://www.geeksforgeeks.org/pandas/slicing-indexing-manipulating-and-cleaning-pandas-dataframe/)

In [ ]:
player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salart'])
df

            Name  Age  Weight   Salart
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

## Slicing Using iloc[] (Integer-Based Indexing)

### Slicing Rows in dataframe

Row slicing means selecting a specific set of rows from the DataFrame while keeping all columns.

In [ ]:
df1 = df.iloc[0:4]
df1

            Name  Age  Weight   Salart
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000

### Slicing Columns in dataframe

Column slicing means selecting a specific set of columns from the DataFrame while keeping all rows.

In [ ]:
df1 = df.iloc[:, 0:2]
df1

            Name  Age
0      M.S.Dhoni   36
1  A.B.D Villers   38
2        V.Kohli   31
3        S.Smith   34
4        C.Gayle   40
5         J.Root   33
6     K.Peterson   42

### Selecting a Specific Cell in a Pandas DataFrame

If you need a single value from a DataFrame you can specify the exact row and column position

In [ ]:
value = df.iloc[2,3]
print("Specific Cell Value:", value)

Specific Cell Value: 8428000

### Using Boolean Conditions in a Pandas DataFrame

In [ ]:
data = df[df['Age'] > 35].iloc[:, :]
print("\nFiltered Data based on Age > 35:\n", data)

Filtered Data based on Age > 35:
             Name  Age  Weight   Salart
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
4        C.Gayle   40     100  4528000
6     K.Peterson   42      85  2528000

## Slicing Using loc[]

### Slicing Rows in Dataframe

With loc[] we can extract a range of rows by their labels instead of integer positions.

In [ ]:
df.set_index('Name', inplace=True)

custom = df.loc['A.B.D Villers':'J.Root']
print(custom)

               Age  Weight   Salart
Name
A.B.D Villers   38      74  3428000
V.Kohli         31      70  8428000
S.Smith         34      80  4428000
C.Gayle         40     100  4528000
J.Root          33      72  7028000

In [ ]:
value = df.loc['V.Kohli', 'Salart']
print("\nValue of the Specific Cell (V.Kohli, Salary):", value)

Value of the Specific Cell (V.Kohli, Salary): 8428000

# [Filter Pandas Dataframe with multiple conditions](https://www.geeksforgeeks.org/python/filter-pandas-dataframe-with-multiple-conditions/)

In [ ]:
# assign data
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],

                          'Age': [30, 35, 37, 33, 34, 30],

                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],

                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

# display dataframe
display(dataFrame)

         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

In [ ]:
display(
    dataFrame.loc[
        (dataFrame['Salary'] >= 10000) &
        (dataFrame['Age'] < 40) &
        (dataFrame['JOB'].str.startswith('D')),
        ['Name', 'JOB']
    ]
)

        Name       JOB
0   RACHEL    DESIGNER

## Filter Pandas Dataframe Using NumPy

In [ ]:
filtered_values = np.where(
    (dataFrame['Salary'] >= 100000) &
    (dataFrame['Age'] < 40) &
    (dataFrame['JOB'].str.startswith('D'))
)
print(filtered_values)
dataFrame.loc[filtered_values]

(array([0]),)

        Name  Age  Salary       JOB
0   RACHEL     30  100000  DESIGNER

## Filter Pandas Dataframe Using Query (eval and query works only with columns)

In [ ]:
filtered_query = dataFrame.query(
    'Salary <= 100000 & Age < 40 & JOB.str.startswith("C").values'
)
filtered_query

        Name  Age  Salary   JOB
1   MONICA     35   93000  CHEF

## Pandas Boolean indexing multiple conditions standard way <br>
("Boolean indexing" works with values in a column only)

In [ ]:
dataFrame[
    (dataFrame['Salary'] >= 100000) &
    (dataFrame['Age'] < 40) &
    dataFrame['JOB'].str.startswith('P')
] [['Name', 'Age', 'Salary']]

         Name  Age  Salary
3    ROSS       33  120000

# Pandas Merging, Joining and Concatenating

## Concatenating DataFrames

### 1. Concatenating DataFrame using .concat()

In [ ]:
data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[4, 5, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [ ]:
frames = [df, df1]
res1 = pd.concat(frames)
res1

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

### 2. Concatenating DataFrames by Setting Logic on Axe

We can modify the concatenation by setting logic on the axes. Specifically we can choose whether to take the **Union (join='outer')** or **Intersection (join='inner')** of columns.

In [ ]:
data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]}

data2 = {'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification  Mobile No
0     Jai   27     Nagpur           Msc         97
1  Princi   24     Kanpur            MA         91
2  Gaurav   22  Allahabad           MCA         58
3    Anuj   32    Kannuaj           Phd         76

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
3    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000

Now we set axes **join = inner** for intersection of dataframe which keeps only the common columns.

* axis=1 → column-wise concat (side by side)
* join='inner' → keep only common index values

👉 So it:

* Matches rows by index
* Keeps only rows where both df and df1 have the same index

In [ ]:
res2 = pd.concat([df, df1], axis=1, join='inner')

res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
2,Gaurav,22,Allahabad,MCA,58,Gaurav,22,Allahabad,MCA,1000
3,Anuj,32,Kannuaj,Phd,76,Anuj,32,Kannuaj,Phd,2000

axis=0 → row-wise concat (stacking)
* One DataFrame goes below the other

join='inner' → keep only common columns

In [ ]:
res2 = pd.concat([df, df1], axis=0, join='inner')

res2

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [ ]:
res2 = pd.concat([df, df1], axis=1, sort=False)
res2 # union by default

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
0,Jai,27.0,Nagpur,Msc,97.0,NaN,NaN,NaN,NaN,NaN
1,Princi,24.0,Kanpur,MA,91.0,NaN,NaN,NaN,NaN,NaN
2,Gaurav,22.0,Allahabad,MCA,58.0,Gaurav,22.0,Allahabad,MCA,1000.0
3,Anuj,32.0,Kannuaj,Phd,76.0,Anuj,32.0,Kannuaj,Phd,2000.0
6,NaN,NaN,NaN,NaN,NaN,Dhiraj,12.0,Allahabad,Bcom,3000.0
7,NaN,NaN,NaN,NaN,NaN,Hitesh,52.0,Kannuaj,B.hons,4000.0

### 3. Concatenating DataFrames by Ignoring Indexes

In [ ]:
# res = pd.concat([df, df1]) # 0 1 2 3 2 3 6 7 -> indexes repeated
res = pd.concat([df, df1], ignore_index=True)
res # indexes continuous

     Name  Age    Address Qualification  Mobile No  Salary
0     Jai   27     Nagpur           Msc       97.0     NaN
1  Princi   24     Kanpur            MA       91.0     NaN
2  Gaurav   22  Allahabad           MCA       58.0     NaN
3    Anuj   32    Kannuaj           Phd       76.0     NaN
4  Gaurav   22  Allahabad           MCA        NaN  1000.0
5    Anuj   32    Kannuaj           Phd        NaN  2000.0
6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

### 4. Concatenating DataFrame with group keys :

In [ ]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name':['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
        'Age':[17, 14, 12, 52],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1,index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[4, 5, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

Here we will use keys as an argument. The keys argument creates a hierarchical index where each row is labeled with the source DataFrame (df1 or df2).

In [ ]:
frames = [df, df1]

res = pd.concat(frames, keys=['df', 'df1'])
res

         Name  Age    Address Qualification
df  0     Jai   27     Nagpur           Msc
    1  Princi   24     Kanpur            MA
    2  Gaurav   22  Allahabad           MCA
    3    Anuj   32    Kannuaj           Phd
df1 4    Abhi   17     Nagpur         Btech
    5  Ayushi   14     Kanpur           B.A
    6  Dhiraj   12  Allahabad          Bcom
    7  Hitesh   52    Kannuaj        B.hons

### 5. Concatenating Mixed DataFrames and Series

In [ ]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df = pd.DataFrame(data1,index=[0, 1, 2, 3])

s1 = pd.Series([1000, 2000, 3000, 4000], name='Salary')

print(df, "\n\n", s1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

 0    1000
1    2000
2    3000
3    4000
Name: Salary, dtype: int64

In [ ]:
res = pd.concat([df, s1], axis=1)
res

     Name  Age    Address Qualification  Salary
0     Jai   27     Nagpur           Msc    1000
1  Princi   24     Kanpur            MA    2000
2  Gaurav   22  Allahabad           MCA    3000
3    Anuj   32    Kannuaj           Phd    4000

## Merging DataFrame

We can merge DataFrames based on a common column by using the on argument. This allows us to combine the DataFrames where values in a specific column match.

In [ ]:
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)


print(df, "\n\n", df1)

  key    Name  Age
0  K0     Jai   27
1  K1  Princi   24
2  K2  Gaurav   22
3  K3    Anuj   32

   key    Address Qualification
0  K0     Nagpur         Btech
1  K1     Kanpur           B.A
2  K2  Allahabad          Bcom
3  K3    Kannuaj        B.hons

### 1.Now here we are using .merge() with one unique key combination.

In [ ]:
res = pd.merge(df, df1, on='key')

res

  key    Name  Age    Address Qualification
0  K0     Jai   27     Nagpur         Btech
1  K1  Princi   24     Kanpur           B.A
2  K2  Gaurav   22  Allahabad          Bcom
3  K3    Anuj   32    Kannuaj        B.hons

### 2. Merging DataFrames Using Multiple Keys

In [ ]:
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)


print(df, "\n\n", df1)

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons

Now we merge dataframe using multiple keys.

In [ ]:
res1 = pd.merge(df, df1, on=['key', 'key1'])
res1

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

### 3. Merging DataFrames Using the how Argument

We use how argument to merge specifies how to find which keys are to be included in the resulting table. If a key combination does not appear in either the left or right tables, the values in the joined table will be NA.

Now we set how = 'left' in order to use keys from left frame only. In this it includes all rows from the left DataFrame and only matching rows from the right.

In [ ]:
res = pd.merge(df, df1, how='left', on=['key', 'key1'])
res

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K1   K1  Princi   24        NaN           NaN
2  K2   K0  Gaurav   22  Allahabad          Bcom
3  K3   K1    Anuj   32        NaN           NaN

Now we set how = 'right' in order to use keys from right frame only. In this it includes all rows from the right DataFrame and only matching rows from the left.

In [ ]:
res1 = pd.merge(df, df1, how='right', on=['key', 'key1'])
res1

  key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur           B.A
2  K2   K0  Gaurav  22.0  Allahabad          Bcom
3  K3   K0     NaN   NaN    Kannuaj        B.hons

 Now we set how = 'outer' in order to get union of keys from dataframes. In this it combines all rows from both DataFrames, filling missing values with NaN.

In [ ]:
res2 = pd.merge(df, df1, how='outer', on=['key', 'key1'])
res2

  key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur           B.A
2  K1   K1  Princi  24.0        NaN           NaN
3  K2   K0  Gaurav  22.0  Allahabad          Bcom
4  K3   K0     NaN   NaN    Kannuaj        B.hons
5  K3   K1    Anuj  32.0        NaN           NaN

Now we set how = 'inner' in order to get intersection of keys from dataframes. In this it only includes rows where there is a match in both DataFrames.

In [ ]:
res3 = pd.merge(df, df1, how='inner', on=['key', 'key1'])
res3

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

# Joining DataFrame

## 1. Joining DataFrames Using .join()

If both DataFrames have the same index, we can use the .join() function to combine their columns. This method is useful when we want to merge DataFrames based on their row indexes rather than columns.

In [ ]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32]}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1,index=['K0', 'K1', 'K2', 'K3'])

df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])


print(df, "\n\n", df1)

      Name  Age
K0     Jai   27
K1  Princi   24
K2  Gaurav   22
K3    Anuj   32

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

In [ ]:
res = df.join(df1)
res

      Name  Age    Address Qualification
K0     Jai   27  Allahabad           MCA
K1  Princi   24        NaN           NaN
K2  Gaurav   22    Kannuaj           Phd
K3    Anuj   32  Allahabad          Bcom

Now we use how = 'outer' in order to get union

In [ ]:
res1 = df.join(df1, how='outer')
res1

      Name   Age    Address Qualification
K0     Jai  27.0  Allahabad           MCA
K1  Princi  24.0        NaN           NaN
K2  Gaurav  22.0    Kannuaj           Phd
K3    Anuj  32.0  Allahabad          Bcom
K4     NaN   NaN    Kannuaj        B.hons

### 2. Joining DataFrames Using the "on" Argument

If we want to join DataFrames based on a column (rather than the index), we can use the on argument. This allows us to specify which column(s) should be used to align the two DataFrames.

In [ ]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Key':['K0', 'K1', 'K2', 'K3']}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])


print(df, "\n\n", df1)

     Name  Age Key
0     Jai   27  K0
1  Princi   24  K1
2  Gaurav   22  K2
3    Anuj   32  K3

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

In [ ]:
res2 = df.join(df1, on='Key')
res2

     Name  Age Key    Address Qualification
0     Jai   27  K0  Allahabad           MCA
1  Princi   24  K1        NaN           NaN
2  Gaurav   22  K2    Kannuaj           Phd
3    Anuj   32  K3  Allahabad          Bcom

### 3. Joining DataFrames with Different Index Levels (Multi-Index)

In some cases, we may be working with DataFrames that have multi-level indexes. The .join() function also supports joining DataFrames that have different index levels by specifying the index levels.

In [ ]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav'],
        'Age':[27, 24, 22]}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kanpur'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1, index=pd.Index(['K0', 'K1', 'K2'], name='key'))

index = pd.MultiIndex.from_tuples([('K0', 'Y0'), ('K1', 'Y1'),
                                   ('K2', 'Y2'), ('K2', 'Y3')],
                                   names=['key', 'Y'])

df1 = pd.DataFrame(data2, index= index)


print(df, "\n\n", df1)

       Name  Age
key
K0      Jai   27
K1   Princi   24
K2   Gaurav   22

           Address Qualification
key Y
K0  Y0  Allahabad           MCA
K1  Y1    Kannuaj           Phd
K2  Y2  Allahabad          Bcom
    Y3     Kanpur        B.hons

In [ ]:
result = df.join(df1, how='inner')
result

          Name  Age    Address Qualification
key Y
K0  Y0     Jai   27  Allahabad           MCA
K1  Y1  Princi   24    Kannuaj           Phd
K2  Y2  Gaurav   22  Allahabad          Bcom
    Y3  Gaurav   22     Kanpur        B.hons

# Sorting Pandas DataFrame

Parameters of sort_values():
* **by**: Specifies the column to sort by.
* **ascending**: A boolean (True for ascending, False for descending).
* **inplace**: If True, the original DataFrame is modified otherwise a new sorted DataFrame is returned.
* **na_position**: Controls where NaN values are placed. Use 'first' to put NaNs at the top or 'last' (default) to place them at the end.
* **ignore_index**: If True, resets the index after sorting.

## 1. Sorting a DataFrame by a Single Column

The sort_values() method in Pandas makes it easy to sort our DataFrame by a single column. By default, it sorts in ascending order but we can customize this.

In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age')
sorted_df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

If we need the sorting to be in descending order simply pass ascending=False:

In [ ]:
sorted_df = df.sort_values(by='Age', ascending=False)
sorted_df

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

## 2. Sorting a DataFrame by Multiple Columns

This is useful when we want to sort by one column like age and if there are ties, sort by another column like salary.

In [ ]:
sorted_df = df.sort_values(by=['Age', 'Score'])
sorted_df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

This will sort first by Age and if multiple rows have the same Age, it will then sort those rows by Salary.

## 3. Sorting DataFrame with Missing Values

In real-world datasets, missing values (NaNs) are common. By default sort_values() places NaN values at the end. If we need them at the top, we can use the na_position parameter.

In [ ]:
data_with_nan = {"Name": ["Alice", "Bob", "Charlie", "David"],
                 "Age": [28, 22, None, 22]}

df_nan = pd.DataFrame(data_with_nan)

sorted_df = df_nan.sort_values(by='Age', na_position="first")
sorted_df

      Name   Age
2  Charlie   NaN
1      Bob  22.0
3    David  22.0
0    Alice  28.0

This will ensure that any rows with missing values in the Age column are placed at the top of the DataFrame.

##4. Sorting by Index

In addition to sorting by column values, we may also want to sort a DataFrame based on its index. This can be done using the sort_index() method in Pandas. By default, sort_index() sorts the DataFrame based on the index in ascending order.

In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

# df_sorted_by_index = df.sort_index() # Ascending by index
df_sorted_by_index = df.sort_index(ascending=False)
df_sorted_by_index

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

## 5. Choosing a Sorting Algorithm

### 1. QuickSort (kind='quicksort'):

In [ ]:
sorted_df = df.sort_values(by='Age', kind='quicksort')
sorted_df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

<h3>2. MergeSort (kind='mergesort'):</h3>

In [ ]:
sorted_df = df.sort_values(by='Age', kind='mergesort')
sorted_df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

<h3>3. HeapSort (kind= 'heapsort'):</h3>

In [ ]:
sorted_df = df.sort_values(by='Age', kind='heapsort')
sorted_df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

<h1>6. Applying Custom Sorting Logic</h1>

In [ ]:
sorted_df = df.sort_values(by='Name', key=lambda col: col.str.lower())
sorted_df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

<h1>Pivot Table in Pandas</h1>

In [ ]:
# creating dataframe
df = pd.DataFrame({'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana',
                               'Beans', 'Orange', 'Broccoli', 'Banana'],
                   'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit',
                                'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
                   'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
                   'Amount': [270, 239, 617, 384, 626, 610, 62, 90]})
df

    Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90

<h2>Create a Pivot Table in Pandas</h2>

<h3>Example 1: Get the Total Sales of Each Product<h3>

In this example, the DataFrame 'df' is transformed using a pivot table, aggregating the total 'Amount' for each unique 'Product' and displaying the result with the sum of amounts for each product.

In [ ]:
pivot = df.pivot_table(index=['Product'],
                       values=['Amount'],
                       aggfunc='sum')
pivot

          Amount
Product
Banana      1091
Beans        626
Broccoli     301
Carrots      270
Orange       610

<h3>Example 2: Get the Total Sales of Each Category</h3>

In this example, a pivot table is created from the DataFrame 'df' to summarize the total 'Amount' sales for each unique 'Category,' employing the 'sum' aggregation function, and the result is printed.

In [ ]:
# creating pivot table of total
# sales category-wise aggfunc = 'sum'
pivot = df.pivot_table(index=['Category'],
                       values=['Amount'],
                       aggfunc='sum')
pivot

           Amount
Category
Fruit        1701
Vegetable    1197

<h3>Example 3: Get Total Sales by Category and Product Both</h3>

In this example, a pivot table is generated from the DataFrame 'df' to showcase the total 'Amount' sales for unique combinations of 'Product' and 'Category,' utilizing the 'sum' aggregation function. The resulting pivot table is then printed.

In [ ]:
pivot = df.pivot_table(index=['Product', 'Category'],
                       values=['Amount'],
                       aggfunc='sum')
pivot

                    Amount
Product  Category
Banana   Fruit        1091
Beans    Vegetable     626
Broccoli Vegetable     301
Carrots  Vegetable     270
Orange   Fruit         610

<h3>Example 4: Get the Mean, Median, Minimum Sale by Category</h3>

In this example, a pivot table is created from the DataFrame 'df' to display the median, mean, and minimum 'Amount' values categorized by 'Category.' The aggregation functions 'median,' 'mean,' and 'min' are applied, and the resulting pivot table is printed.

In [ ]:
# 'mean', 'min'} will get median, mean and
# minimum of sales respectively
pivot = df.pivot_table(index=['Category'],
                       values=['Amount'],
                       aggfunc={'median', 'mean', 'min'})
pivot

           Amount
             mean median min
Category
Fruit      425.25  497.0  90
Vegetable  299.25  254.5  62

<h3>Example 5: Get the Mean, Median, Minimum Sale by Product</h3>

In this example, a pivot table is generated from the DataFrame 'df' to showcase the median, mean, and minimum 'Amount' values for each unique 'Product.' The aggregation functions 'median,' 'mean,' and 'min' are applied, resulting in the pivot table, which is then printed.

In [ ]:
pivot = df.pivot_table(index=['Product'],
                       values=['Amount'],
                       aggfunc={'median', 'mean', 'min'})
pivot

              Amount
                mean median  min
Product
Banana    363.666667  384.0   90
Beans     626.000000  626.0  626
Broccoli  150.500000  150.5   62
Carrots   270.000000  270.0  270
Orange    610.000000  610.0  610